spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/distance-calculator
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  liquibase:
    change-log: /db/changelog/db.changelog-master.xml


server:
  port: 8888